### ISSUE TITLE
SerperDevTool is missing

### ISSUE THREAD

**Issue by ombhojane** [crewAIInc/crewAI-tools#105]
## Problem:
I did imports search on crewai_tools package and found that 'SerperDevTool' not exists in the crewai_tools package, despite being referenced in the documentation

![image](https://github.com/user-attachments/assets/6adae3af-a44e-4fc3-bb25-d27dab294668)

## Expected Behavior
SerperDevTool should be available for import from crewai_tools.

## Actual Behavior
SerperDevTool is not listed among the available imports and causes an ImportError when attempting to import.

I'm planning to create a SerperDevTool function to leverage the Serper API and perform its intended function. However, before proceeding, I'd like to understand:

1. Is SerperDevTool intentionally removed or renamed?
2. Are there any existing plans to reimplement this tool?
3. Are there any specific guidelines or best practices I should follow when creating this tool?

## Request for Guidance
Can you provide any information or issue references about the original implementation or intended functionality of SerperDevTool?

**Comment by theCyberTech** [comment]
what version are you on?

**Comment by ombhojane** [comment]
I was at 0.0.6, and latest version is 2.xx.xx
