### ISSUE TITLE
On v0.76.2, CodeInterpreterTool() errors on execution of code

### ISSUE THREAD

**Issue by ChristopherPeterson** [crewAIInc/crewAI-tools#118]
Error I get when using CodeInterpreterTool(), and I'm not sure how I should proceed when CodeInterpreterSchema seems to be an internal class to that tool's module.

I encountered an error while trying to use the tool. This was the error: 1 validation error for CodeInterpreterSchema
libraries_used
  Input should be a valid list [type=list_type, input_value='pandas', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/list_type.
 Tool Code Interpreter accepts these inputs: Code Interpreter(code: 'string', libraries_used: 'array') - Interprets Python3 code strings with a final print statement. code: 'Python3 code used to be interpreted in the Docker container. ALWAYS PRINT the final result and the output of the code', libraries_used: 'List of libraries used in the code with proper installing names separated by commas. Example: numpy,pandas,beautifulsoup4'

**Comment by ChristopherPeterson** [comment]
If this helps, I'm using LLM model "bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0"

**Comment by joaomdmoura** [comment]
cc future @bhancockio

**Comment by bhancockio** [comment]
Good morning @ChristopherPeterson!

There was a tool calling error introduced in 0.76.0 and we resolved it in 0.76.9.

If you update to 0.76.9, the error should go away.

I'm going to close this issue out. If it still persists on the new model, please let us know!
