### ISSUE TITLE
Open to contributing new tools?

### ISSUE THREAD

**Issue by burningion** [crewAIInc/crewAI-tools#126]
Hey there,

I'm building out an Agent using crewAI, and I'd like to (potentially) contribute some tools that I write. I'm working on video generation, and these tools would allow for video editing, analysis, etc.

And if you're not open to accepting contributed tools, how might one get added to a directory of compatible tools?

I tried looking for the answers to these questions in this repo, but didn't see them. I'd suggest addressing these questions in the `README.md`?

**Comment by theCyberTech** [comment]
Hi @burningion 

Feel free to raise a PR for any tools you have created and we will asses / review / approve them

Thanks for contributing
