### ISSUE TITLE
Simple filewrite code is failing 

### ISSUE THREAD

**Issue by ashitabh** [crewAIInc/crewAI-tools#138]
Getting the following error for a simple filewriter  ""An error occurred while writing to the file: 'bool' object has no attribute 'lower'"
I can't find where is the lower function used in the whole codebase

from crewai_tools import FileWriterTool

# Initialize the tool
file_writer_tool = FileWriterTool()
# Write content to a file in a specified directory
result = file_writer_tool._run(filename='ai.txt', content = "hello", directory = "", overwrite=True)
print(result)

**Comment by theCyberTech** [comment]
Hi can you do this instead

```overwrite="True"```

this is because the tool expects the  overwrite param the be a string NOT BOOL, I will look into fixing this as well to accept BOOL
