### ISSUE TITLE
Explain how the Web Site Search Tool works

### ISSUE THREAD

**Issue by vbabaytsev** [crewAIInc/crewAI-tools#31]
Hi!
I'm trying to use the Web Site Search Tool, but it always gives an empty result. Could you please explain how to use it correctly? I couldn't find any examples of how to use it in the documentation. Only examples of initialization.

**Comment by strnad** [comment]
it works, but only when you pass the "website" parameter when you make instance of the tool. passing of the parameter by agent is probably broken now :-/ and that issue affect not only websitesearch tool but also many (maybe all) other RAGtool based tools

**Comment by strnad** [comment]
fixed in https://github.com/joaomdmoura/crewAI-tools/pull/49

**Comment by strnad** [comment]
@vbabaytsev the fix is merged, it should work now ;)

**Comment by joaomdmoura** [comment]
New version is out as well :D
